name: myenv
dependencies:
  - python=3.8.1
  - pip=20.0.*
  - pip:
      - azureml==0.2.7
      - azureml-core==1.30.0
      - azureml-defaults==1.30.0
      - azureml-sdk==1.30.0
      - python-decouple==3.5
      - snowflake-connector-python[pandas]==2.7.3
      - snowflake-sqlalchemy==1.3.3
      - SQLAlchemy==1.4.35
      - PyYAML==6.0
